/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { PostCreateNestedManyWithoutUsersInput } from "./PostCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { ProductCreateNestedManyWithoutUsersInput } from "./ProductCreateNestedManyWithoutUsersInput";
import { HouseCreateNestedManyWithoutUsersInput } from "./HouseCreateNestedManyWithoutUsersInput";
import { JobCreateNestedManyWithoutUsersInput } from "./JobCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  profilePicture?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => PostCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PostCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PostCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  posts?: PostCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ProductCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ProductCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ProductCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  products?: ProductCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => HouseCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => HouseCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => HouseCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  houses?: HouseCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => JobCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => JobCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => JobCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  jobs?: JobCreateNestedManyWithoutUsersInput;
}

export { UserCreateInput as UserCreateInput };
